Lock Chrome to v76 for 3.11 console tests

diff --git a/sjb/config/test_cases/test_branch_origin_web_console_311.yml b/sjb/config/test_cases/test_branch_origin_web_console_311.yml
--- a/sjb/config/test_cases/test_branch_origin_web_console_311.yml
+++ b/sjb/config/test_cases/test_branch_origin_web_console_311.yml
@@ -15,14 +15,34 @@ extensions:
       title: "start openshift server"
       repository: "origin"
       script: |-
-        wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
-        sudo yum install ./google-chrome-stable_current_*.rpm -y
         oc version
         oc cluster up --public-hostname=localhost --loglevel=5 --server-loglevel=5
     - type: "script"
       title: "run web console tests"
       repository: "origin-web-console"
       script: |-
+        # Chrome Version 76.0.3809.0 (Developer Build) (64-bit)
+        # https://omahaproxy.appspot.com/
+        BRANCH_BASE="665006"
+        BRANCH_SHA256SUM="a1ae2e0950828f991119825f62c24464ab3765aa219d150a94fb782a4c66a744"
+        CHROME_DIR="/tmp/__chrome_browser__"
+        CHROME_DOWNLOAD_URL="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots"
+
+        # download
+        mkdir -p "${CHROME_DIR}/${BRANCH_BASE}"
+        curl -G "${CHROME_DOWNLOAD_URL}/o/Linux_x64%2F${BRANCH_BASE}%2Fchrome-linux.zip" \
+            -d "alt=media" \
+            > "${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip"
+        unzip "${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip" -d "${CHROME_DIR}/${BRANCH_BASE}"
+
+        # check sha256sum
+        if [ "$(sha256sum ${CHROME_DIR}/chrome-linux-${BRANCH_BASE}.zip | cut -f 1 -d ' ')" != "${BRANCH_SHA256SUM}" ];
+        then
+          echo "ERROR: chrmoe binary sha256 missmatch"
+          exit 1
+        fi
+
+        export CHROME_BIN="${CHROME_DIR}/${BRANCH_BASE}/chrome-linux/chrome"
         export PATH=$PATH:$(pwd)/node_modules/.bin
         make test
   post_actions:
