sign-artifacts: fix formatting

diff --git a/jobs/signing/sign-artifacts/Jenkinsfile b/jobs/signing/sign-artifacts/Jenkinsfile
--- a/jobs/signing/sign-artifacts/Jenkinsfile
+++ b/jobs/signing/sign-artifacts/Jenkinsfile
@@ -208,22 +208,22 @@ node {
 
                     // transform the file into a directory containing the
                     // file, mirror to google.
-		    //
-		    // Notes on gsutil options:
-		    // -n - no clobber/overwrite
-		    // -v - print url of item
-		    // -L - write to log for auto re-processing
-		    // -r - recursive
+		            //
+		            // Notes on gsutil options:
+		            // -n - no clobber/overwrite
+		            // -v - print url of item
+		            // -L - write to log for auto re-processing
+		            // -r - recursive
                     commonlib.shell("""
                         for file in sha256=*; do
-                            mv $file ${params.SIGNATURE_NAME}
-                            mkdir $file
-                            mv ${params.SIGNATURE_NAME} $file
+                            mv \$file \${params.SIGNATURE_NAME}
+                            mkdir \$file
+                            mv ${params.SIGNATURE_NAME} \$file
                             i=1
-                            until gsutil cp -n -v -L cp.log -r $file gs://openshift-release/official/signatures/openshift/release; do
+                            until gsutil cp -n -v -L cp.log -r \$file gs://openshift-release/official/signatures/openshift/release; do
                                 sleep 1
-                                i=$(( $i + 1))
-                                if [ $i -eq 10 ]; then echo "Failed to mirror to google after 10 attempts. Giving up."; exit 1; fi
+                                i=\$(( \$i + 1 ))
+                                if [ \$i -eq 10 ]; then echo "Failed to mirror to google after 10 attempts. Giving up."; exit 1; fi
                             done
                         done
                     """)
