fix escape

diff --git a/jobs/signing/sign-artifacts/Jenkinsfile b/jobs/signing/sign-artifacts/Jenkinsfile
--- a/jobs/signing/sign-artifacts/Jenkinsfile
+++ b/jobs/signing/sign-artifacts/Jenkinsfile
@@ -217,19 +217,19 @@ node {
 		            // -v - print url of item
 		            // -L - write to log for auto re-processing
 		            // -r - recursive
-                    commonlib.shell("""
+                    commonlib.shell('''
                         for file in sha256=*; do
-                            mv \$file \${params.SIGNATURE_NAME}
-                            mkdir \$file
-                            mv ${params.SIGNATURE_NAME} \$file
+                            mv $file ${params.SIGNATURE_NAME}
+                            mkdir $file
+                            mv ${params.SIGNATURE_NAME} $file
                             i=1
-                            until gsutil cp -n -v -L cp.log -r \$file gs://openshift-release/official/signatures/openshift/release; do
+                            until gsutil cp -n -v -L cp.log -r $file gs://openshift-release/official/signatures/openshift/release; do
                                 sleep 1
-                                i=\$(( \$i + 1 ))
-                                if [ \$i -eq 10 ]; then echo "Failed to mirror to google after 10 attempts. Giving up."; exit 1; fi
+                                i=$(( $i + 1 ))
+                                if [ $i -eq 10 ]; then echo "Failed to mirror to google after 10 attempts. Giving up."; exit 1; fi
                             done
                         done
-                    """)
+                    ''')
                     sshagent(["openshift-bot"]) {
                         MIRROR_PATH = "openshift-v4/signatures/openshift/release"
                         sh "rsync -avzh -e \"ssh -o StrictHostKeyChecking=no\" sha256=* ${MIRROR_TARGET}:/srv/pub/${MIRROR_PATH}/"
