update test_branch_origin_extended_conformance_install_upgrade.yml to work with install_upgrade script

diff --git a/config/test_cases/test_branch_origin_extended_conformance_install_update.yml b/config/test_cases/test_branch_origin_extended_conformance_install_update.yml
--- a/config/test_cases/test_branch_origin_extended_conformance_install_update.yml
+++ b/config/test_cases/test_branch_origin_extended_conformance_install_update.yml
@@ -6,45 +6,123 @@ extensions:
     - name: "aos-cd-jobs"
   actions:
     - type: "script"
-      title: "install origin GA and update"
+      title: "determine the release commit for origin images"
+      repository: "origin"
+      script: |-
+        jobs_repo="/data/src/github.com/openshift/aos-cd-jobs/"
+        git log -1 --pretty=%h > "${jobs_repo}/ORIGIN_COMMIT"
+        source hack/lib/init.sh
+        os::build::rpm::format_nvra > "${jobs_repo}/ORIGIN_BUILT_VERSION"
+    - type: "script"
+      title: "build an openshift-ansible release"
+      repository: "openshift-ansible"
+      script: |-
+        tito_tmp_dir="tito"
+        mkdir -p "${tito_tmp_dir}"
+        tito tag --offline --accept-auto-changelog
+        tito build --output="${tito_tmp_dir}" --rpm --test --offline --quiet
+        createrepo "${tito_tmp_dir}/noarch"
+        cat << EOR > ./openshift-ansible-local-release.repo
+        [openshift-ansible-local-release]
+        baseurl = file://$( pwd )/${tito_tmp_dir}/noarch
+        gpgcheck = 0
+        name = OpenShift Ansible Release from Local Source
+        EOR
+        sudo cp ./openshift-ansible-local-release.repo /etc/yum.repos.d
+        basename "${tito_tmp_dir}"/noarch/atomic-openshift-utils*.rpm .rpm > /data/src/github.com/openshift/aos-cd-jobs/OPENSHIFT_ANSIBLE_BUILT_VERSION
+    - type: "script"
+      title: "install ansible atomic-openshift-utils"
       repository: "aos-cd-jobs"
       script: |-
         pkg_name="origin"
-        sudo yum install -y ansible-2.2.0.0
         git checkout sjb
-        general_yml_file=inventory/group_vars/OSEv3/general.yml
-        if [ $pkg_name = "atomic-openshift" ]
+        echo $pkg_name > PKG_NAME
+        echo "openshift-ansible openshift-ansible-callback-plugins openshift-ansible-docs openshift-ansible-filter-plugins openshift-ansible-lookup-plugins openshift-ansible-playbooks openshift-ansible-roles" > OPENSHIFT_ANSIBLE_PKGS
+        sudo python hack/determine_install_upgrade_version.py $( cat OPENSHIFT_ANSIBLE_BUILT_VERSION ) > OPENSHIFT_ANSIBLE_VARS
+        source OPENSHIFT_ANSIBLE_VARS
+        versioned_packages_to_install=""
+        if [[ ${ATOMIC_OPENSHIFT_UTILS_INSTALL_MINOR_VERSION} -le 4 ]]
         then
-          sed -i "s/deployment_type:.*/deployment_type: \"openshift-enterprise\" /g" $general_yml_file
+          sudo yum erase -y ansible
+          versioned_packages_to_install="ansible-2.2.0.0"
         fi
-        openshift_pkgs=( $pkg_name openshift-ansible-playbooks )
-        for pkg in "${openshift_pkgs[@]}"
+        packages_to_install=( $( cat ./OPENSHIFT_ANSIBLE_PKGS ) )
+        for pkg in "${packages_to_install[@]}"
         do
-          sudo python hack/get_available_pkgs.py $pkg > "all_${pkg}_versions"
-          sed -i '/^[a-zA-Z]/d' all_${pkg}_versions
-          sort -u -o all_${pkg}_versions all_${pkg}_versions
-          cat all_${pkg}_versions
+          versioned_packages_to_install+=" ${pkg}-${ATOMIC_OPENSHIFT_UTILS_INSTALL_VERSION}"
         done
-        current_openshift_version=$(tail -n1 all_${pkg_name}_versions | awk -F'-' '{print $1}')
-        echo "current version -> $current_openshift_version"
-        current_openshift_major_version=$(echo $current_openshift_version | awk -F'.' '{print $1}')
-        current_openshift_minor_version=$(echo $current_openshift_version | awk -F'.' '{print $2}')
-        latest_version=$current_openshift_major_version.$(($current_openshift_minor_version + 1))
-        all_current_openshift_versions_array=($(cat "all_${pkg_name}_versions" | grep "$current_openshift_major_version.$current_openshift_minor_version"))
-        all_current_openshift_ansible_versions_array=($(cat "all_openshift-ansible-playbooks_versions" | grep "^3.$current_openshift_minor_version"))
-        set_openshift_version=$(echo ${all_current_openshift_versions_array[0]})
-        echo "=== Installing openshift-ansible-${all_current_openshift_ansible_versions_array[0]} ==="
-        sudo yum install -y openshift-ansible-playbooks-${all_current_openshift_ansible_versions_array[0]}
-        echo "=== Installing ${pkg_name}-${set_openshift_version} ==="
-        ansible-playbook --become --become-user root --connection local -i inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/network_manager.yml
-        ansible-playbook --become --become-user root --connection local -i inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml -e set_openshift_version="${set_openshift_version}"
-        if [ ${#all_current_openshift_versions_array[@]} -gt 1 ]
+        echo "=== Installing atomic-openshift-utils-${ATOMIC_OPENSHIFT_UTILS_INSTALL_VERSION} packages ==="
+        sudo yum install -y ${versioned_packages_to_install}
+    - type: "script"
+      title: "install Ansible plugins"
+      repository: "origin"
+      script: |-
+        sudo yum install -y python-pip
+        sudo pip install junit_xml
+        sudo chmod o+rw /etc/environment
+        echo "ANSIBLE_JUNIT_DIR=$( pwd )/_output/tests/ansible_junit" >> /etc/environment
+        sudo mkdir -p /usr/share/ansible/plugins/callback
+        for plugin in 'default_with_output_lists' 'generate_junit'; do
+           wget "https://raw.githubusercontent.com/openshift/origin-ci-tool/master/oct/ansible/oct/callback_plugins/${plugin}.py"
+           sudo mv "${plugin}.py" /usr/share/ansible/plugins/callback
+        done
+        sudo sed -r -i -e 's/^#?stdout_callback.*/stdout_callback = default_with_output_lists/' -e 's/^#?callback_whitelist.*/callback_whitelist = generate_junit/' /etc/ansible/ansible.cfg
+    - type: "script"
+      title: "install origin GA and update"
+      repository: "aos-cd-jobs"
+      script: |-
+        pkg_name=$( cat ./PKG_NAME )
+        if [[ "${pkg_name}" == "origin" ]]; then
+            deployment_type="origin"
+        elif [[ "${pkg_name}" == "atomic-openshift" ]]; then
+            deployment_type="openshift-enterprise"
+        else
+            echo "Can't determine deployment type"
+            exit 1
+        fi
+        echo "${deployment_type}" > DEPLOYMENT_TYPE
+        sudo python hack/determine_install_upgrade_version.py $( cat ORIGIN_BUILT_VERSION ) > ORIGIN_VARS
+        source ORIGIN_VARS
+        source OPENSHIFT_ANSIBLE_VARS
+        echo "=== Installing ${pkg_name}-${ORIGIN_INSTALL_VERSION} ==="
+        ansible-playbook  -vv                \
+                          --become           \
+                          --become-user root \
+                          --connection local \
+                          -i inventory/      \
+                          /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-node/network_manager.yml \
+                          -e deployment_type=$( cat ./DEPLOYMENT_TYPE)
+        # Remove "enable_excluders" variable after openshift-ansbile pkgs are rebuilded with https://github.com/openshift/openshift-ansible/pull/3788
+        ansible-playbook  -vv                \
+                          --become           \
+                          --become-user root \
+                          --connection local \
+                          -i inventory/      \
+                          /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml \
+                          -e openshift_pkg_version="-${ORIGIN_INSTALL_VERSION}"         \
+                          -e deployment_type=$( cat ./DEPLOYMENT_TYPE)                  \
+                          -e enable_excluders=false
+        if [[ -v ORIGIN_UPGRADE_VERSION  && -v ATOMIC_OPENSHIFT_UTILS_UPGRADE_VERSION ]]
         then
-          echo "=== Updating openshift-ansible to openshift-ansible-${all_current_openshift_ansible_versions_array[${#all_current_openshift_ansible_versions_array[@]}-1]} ==="
-          sudo yum erase -y openshift-ansible
-          sudo yum install -y openshift-ansible-playbooks-${all_current_openshift_ansible_versions_array[${#all_current_openshift_ansible_versions_array[@]}-1]}
-          echo "=== Updating ${pkg_name} to ${pkg_name}-${all_current_openshift_versions_array[${#all_current_openshift_versions_array[@]}-1]} ==="
-          ansible-playbook --become --become-user root --connection local --inventory inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_${current_openshift_minor_version}/upgrade.yml -e openshift_upgrade_target="${all_current_openshift_versions_array[${#all_current_openshift_versions_array[@]}-1]}"
+          echo "=== Updating atomic-openshift-utils-${ATOMIC_OPENSHIFT_UTILS_UPGRADE_VERSION} ==="
+          versioned_packages_to_install=""
+          packages_to_install=( $( cat ./OPENSHIFT_ANSIBLE_PKGS ) )
+          for pkg in "${packages_to_install[@]}"
+          do
+            versioned_packages_to_install+=" ${pkg}-${ATOMIC_OPENSHIFT_UTILS_UPGRADE_VERSION}"
+          done
+          sudo yum upgrade -y ${versioned_packages_to_install}
+          echo "=== Updating ${pkg_name} to ${ORIGIN_UPGRADE_VERSION} ==="
+          upgrade_playbook="/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_${ORIGIN_UPGRADE_MINOR_VERSION}/upgrade.yml"
+          ansible-playbook  -vv                    \
+                            --become               \
+                            --become-user root     \
+                            --connection local     \
+                            --inventory inventory/ \
+                            "${upgrade_playbook}"  \
+                            -e openshift_pkg_version="-${ORIGIN_UPGRADE_VERSION}" \
+                            -e deployment_type=$( cat ./DEPLOYMENT_TYPE)          \
+                            -e oreg_url='openshift/origin-${component}:'"${ORIGIN_UPGRADE_VERSION_PKG_VERSION}"
         fi
     - type: "script"
       title: "build an origin release"
@@ -57,45 +135,34 @@ extensions:
         sed -i 's|go/src|data/src|' _output/local/releases/rpms/origin-local-release.repo
         sudo cp _output/local/releases/rpms/origin-local-release.repo /etc/yum.repos.d/
     - type: "script"
-      title: "build an openshift-ansible release"
-      repository: "openshift-ansible"
-      script: |-
-        tito_tmp_dir="tito"
-        mkdir -p "${tito_tmp_dir}"
-        tito tag --offline --use-version 3.6.0 --accept-auto-changelog
-        tito build --output="${tito_tmp_dir}" --rpm --test --offline --quiet
-        createrepo "${tito_tmp_dir}/noarch"
-        cat << EOR > ./openshift-ansible-local-release.repo
-        [openshift-ansible-local-release]
-        baseurl = file://$( pwd )/${tito_tmp_dir}/noarch
-        gpgcheck = 0
-        name = OpenShift Ansible Release from Local Source
-        EOR
-        sudo cp ./openshift-ansible-local-release.repo /etc/yum.repos.d
-    - type: "script"
-      title: "install the openshift-ansible release"
-      script: |-
-        sudo yum install -y atomic-openshift-utils
-    - type: "script"
-      title: "check out the correct branch of aos-cd-jobs"
+      title: "upgrade openshift-ansible to release"
       repository: "aos-cd-jobs"
       script: |-
-        git checkout sjb
+        source ORIGIN_VARS
+        source OPENSHIFT_ANSIBLE_VARS
+        versioned_packages_to_upgrade=""
+        packages_to_upgrade="$( cat ./OPENSHIFT_ANSIBLE_PKGS )"
+        for pkg in "${packages_to_upgrade[@]}"
+        do
+          versioned_packages_to_upgrade+=" ${pkg}-${ATOMIC_OPENSHIFT_UTILS_UPGRADE_RELEASE_VERSION}"
+        done
+        sudo yum upgrade -y ${versioned_packages_to_upgrade}
     - type: "script"
-      title: "determine the release commit for origin images"
-      repository: "origin"
-      script: |-
-        git log -1 --pretty=%h >> /data/src/github.com/openshift/aos-cd-jobs/ORIGIN_COMMIT
-    - type: "script"
-      title: "update origin"
+      title: "update origin to release"
       repository: "aos-cd-jobs"
       script: |-
-        sudo python hack/get_available_pkgs.py origin > "all_origin_versions"
-        sed -i '/^[a-zA-Z]/d' all_origin_versions
-        sort -u -o all_origin_versions all_origin_versions
-        upgrade_version=$(tail -1 all_origin_versions)
-        upgrade_minor_version=$(echo "${upgrade_version}" | awk -F'.' '{print $2}')
-        ansible-playbook --become --become-user root --connection local --inventory inventory/ /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_${upgrade_minor_version}/upgrade.yml -e openshift_image_tag="$( cat ./ORIGIN_COMMIT )" -e openshift_upgrade_target="${upgrade_version}"
+        pkg_name=$( cat ./PKG_NAME )
+        source ORIGIN_VARS
+        upgrade_playbook="/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_${ORIGIN_UPGRADE_RELEASE_MINOR_VERSION}/upgrade.yml"
+        ansible-playbook  -vv                    \
+                          --become               \
+                          --become-user root     \
+                          --connection local     \
+                          --inventory inventory/ \
+                           "${upgrade_playbook}" \
+                          -e openshift_pkg_version="-${ORIGIN_UPGRADE_RELEASE_VERSION}" \
+                          -e deployment_type=$( cat ./DEPLOYMENT_TYPE) \
+                          -e oreg_url='openshift/origin-${component}:'"$( cat ./ORIGIN_COMMIT )"
     - type: "script"
       title: "expose the kubeconfig"
       script: |-
@@ -106,6 +173,9 @@ extensions:
       repository: "origin"
       script: |-
         KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY='true' JUNIT_REPORT='true' make test-extended SUITE=conformance
+  generated_artifacts:
+    origin_package_history.log: "sudo yum history info origin"
+    openshift_ansible_package_history.log: "sudo yum history info openshift-ansible"
   system_journals:
     - origin-master.service
     - origin-node.service
